name: api action
on: push
jobs:
  check_api_folder:
    name: check api folder
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"
      - name: Install dependencies
        run: yarn install
      - name: testing
        run: npm run test
